"use client";

import type {
  ButtonHTMLAttributes,
  ComponentProps,
  HTMLAttributes,
  ReactElement,
  ReactNode,
  RefObject,
} from "react";
import { createContext, forwardRef, useCallback, useContext, useMemo, useRef } from "react";
import { RiCheckLine, RiFileCopyLine } from "react-icons/ri";

import { buttonVariants } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { cn } from "@/lib/utils";

function mergeRefs<T>(...refs: (React.Ref<T> | undefined)[]) {
  return (value: T | null) => {
    for (const ref of refs) {
      if (typeof ref === "function") ref(value);
      else if (ref) (ref as React.MutableRefObject<T | null>).current = value;
    }
  };
}

import { ScrollArea, ScrollBar } from "./scroll-area";
import { useCopyButton } from "./use-copy-button";

export interface CodeBlockProps extends ComponentProps<"figure"> {
  /**
   * Icon of code block
   *
   * When passed as a string, it assumes the value is the HTML of icon
   */
  icon?: ReactNode;

  /**
   * Allow to copy code with copy button
   *
   * @defaultValue true
   */
  allowCopy?: boolean;

  /**
   * Keep original background color generated by Shiki or Rehype Code
   *
   * @defaultValue false
   */
  keepBackground?: boolean;

  viewportProps?: HTMLAttributes<HTMLElement>;

  /**
   * show line numbers
   */
  "data-line-numbers"?: boolean;

  /**
   * @defaultValue 1
   */
  "data-line-numbers-start"?: number;

  Actions?: (props: { className?: string; children?: ReactNode }) => ReactNode;
}

const TabsContext = createContext<{
  containerRef: RefObject<HTMLDivElement | null>;
  nested: boolean;
} | null>(null);

export function Pre(props: ComponentProps<"pre">) {
  return (
    <pre {...props} className={cn("min-w-full w-max *:flex *:flex-col", props.className)}>
      {props.children}
    </pre>
  );
}

const EMPTY_VIEWPORT_PROPS = {};

export function CodeBlock({
  ref,
  title,
  allowCopy,
  keepBackground = false,
  icon,
  viewportProps = EMPTY_VIEWPORT_PROPS,
  children,
  Actions = (props) => <div {...props} className={cn("empty:hidden", props.className)} />,
  ...props
}: CodeBlockProps) {
  const isTab = useContext(TabsContext) !== null;
  const areaRef = useRef<HTMLDivElement>(null);
  allowCopy ??= !isTab;
  const bg = cn(
    "bg-secondary",
    keepBackground && "bg-(--shiki-light-bg) dark:bg-(--shiki-dark-bg)",
  );
  const onCopy = useCallback(() => {
    const pre = areaRef.current?.getElementsByTagName("pre").item(0);
    if (!pre) return;
    const clone = pre.cloneNode(true) as HTMLElement;
    clone.querySelectorAll(".nd-copy-ignore").forEach((node) => {
      node.remove();
    });
    void navigator.clipboard.writeText(clone.textContent ?? "");
  }, []);
  return (
    <figure
      ref={ref}
      dir="ltr"
      {...props}
      className={cn(
        isTab ? [bg, "rounded-lg"] : "my-4 rounded-lg bg-card",
        "group shiki relative overflow-hidden border text-sm shadow-sm outline-none",
        props.className,
      )}
    >
      {title ? (
        <div
          className={cn(
            "group flex h-9.5 items-center gap-2 bg-muted ps-3 pr-1 text-muted-foreground",
            isTab && "border-b",
          )}
        >
          {typeof icon === "string" ? (
            <div
              className="[&_svg]:size-3.5"
              dangerouslySetInnerHTML={{
                __html: icon,
              }}
            />
          ) : (
            icon
          )}
          <figcaption className="flex-1 truncate">{title}</figcaption>
          {Actions({
            children: allowCopy && <CopyButton onCopy={onCopy} />,
          })}
        </div>
      ) : (
        Actions({
          className: "absolute top-1 right-1 z-2 text-muted-foreground",
          children: allowCopy && <CopyButton onCopy={onCopy} />,
        })
      )}
      <div
        ref={areaRef}
        {...viewportProps}
        className={cn(
          !isTab && [bg, "rounded-none border border-x-0 border-b-0"],
          "max-h-[600px] overflow-auto bg-muted/50 text-sm",
          viewportProps.className,
          !title && "border-t-0",
        )}
        style={
          {
            // space for toolbar
            "--padding-right": !title ? "calc(var(--spacing) * 8)" : undefined,
            counterSet: props["data-line-numbers"]
              ? `line ${Number(props["data-line-numbers-start"] ?? 1) - 1}`
              : undefined,
            ...viewportProps.style,
          } as object
        }
      >
        {children}
      </div>
    </figure>
  );
}
function CopyButton({
  className,
  onCopy,
  ...props
}: ButtonHTMLAttributes<HTMLButtonElement> & {
  onCopy: () => void;
}): ReactElement {
  const [checked, onClick] = useCopyButton(onCopy);

  return (
    <button
      type="button"
      className={cn(
        buttonVariants({
          variant: "ghost",
          size: "icon",
        }),
        "transition-opacity size-7 border-none  group-hover:opacity-100",
        "opacity-0 group-hover:opacity-100",
        "group-hover:opacity-100",
        className,
      )}
      aria-label="Copy Text"
      onClick={onClick}
      {...props}
    >
      <RiCheckLine className={cn("size-3.5 transition-transform", !checked && "scale-0")} />
      <RiFileCopyLine
        className={cn("absolute size-3.5 transition-transform", checked && "scale-0")}
      />
    </button>
  );
}
export function CodeBlockTabs({ ref, ...props }: ComponentProps<typeof Tabs>) {
  const containerRef = useRef<HTMLDivElement>(null);
  const nested = useContext(TabsContext) !== null;

  return (
    <Tabs
      ref={mergeRefs(containerRef, ref)}
      {...props}
      className={cn(
        "overflow-hidden rounded-lg border bg-card p-1",
        !nested && "my-4",
        props.className,
      )}
    >
      <TabsContext.Provider
        value={useMemo(
          () => ({
            containerRef,
            nested,
          }),
          [nested],
        )}
      >
        {props.children}
      </TabsContext.Provider>
    </Tabs>
  );
}
export function CodeBlockTabsList(props: ComponentProps<typeof TabsList>) {
  return (
    <TabsList
      {...props}
      className={cn(
        "flex flex-row overflow-x-auto px-1 -mx-1 text-muted-foreground",
        props.className,
      )}
    >
      {props.children}
    </TabsList>
  );
}

export function CodeBlockTabsTrigger({ children, ...props }: ComponentProps<typeof TabsTrigger>) {
  return (
    <TabsTrigger
      {...props}
      className={cn(
        "group relative inline-flex items-center gap-2 px-2 py-1.5 text-sm font-medium text-nowrap transition-colors first:ms-1 hover:text-accent-foreground data-[state=active]:text-primary [&_svg]:size-3.5",
        props.className,
      )}
    >
      <div className="absolute inset-x-2 bottom-0 h-px group-data-[state=active]:bg-primary" />
      {children}
    </TabsTrigger>
  );
}

// TODO: currently Vite RSC plugin has problem with adding `asChild` here, maybe revisit this in future
export const CodeBlockTab = TabsContent;

export const CodeBlockOld = forwardRef<HTMLElement, CodeBlockProps>(
  ({ title, allowCopy = true, keepBackground = false, icon, viewportProps, ...props }, ref) => {
    const areaRef = useRef<HTMLDivElement>(null);
    const onCopy = useCallback(() => {
      const pre = areaRef.current?.getElementsByTagName("pre").item(0);

      if (!pre) return;

      const clone = pre.cloneNode(true) as HTMLElement;
      clone.querySelectorAll(".nd-copy-ignore").forEach((node) => {
        node.remove();
      });

      void navigator.clipboard.writeText(clone.textContent ?? "");
    }, []);

    return (
      <figure
        ref={ref}
        {...props}
        className={cn(
          "group relative my-6 overflow-hidden rounded-lg border bg-secondary/50 text-sm",
          keepBackground && "bg-[var(--shiki-light-bg)] dark:bg-[var(--shiki-dark-bg)]",
          props.className,
        )}
      >
        {title ? (
          <div className="flex flex-row items-center gap-2 border-b bg-muted px-4 py-1.5">
            {icon ? (
              <div
                className="text-muted-foreground [&_svg]:size-3.5"
                dangerouslySetInnerHTML={
                  typeof icon === "string"
                    ? {
                        __html: icon,
                      }
                    : undefined
                }
              >
                {typeof icon !== "string" ? icon : null}
              </div>
            ) : null}
            <figcaption className="flex-1 truncate text-muted-foreground">{title}</figcaption>
            {allowCopy ? <CopyButton className="-me-2" onCopy={onCopy} /> : null}
          </div>
        ) : (
          allowCopy && (
            <CopyButton className="absolute top-2 right-2 z-[2] backdrop-blur-md" onCopy={onCopy} />
          )
        )}
        <ScrollArea ref={areaRef} dir="ltr">
          <div {...viewportProps} className={cn("max-h-[600px]", viewportProps?.className)}>
            {props.children}
          </div>
          <ScrollBar orientation="horizontal" />
        </ScrollArea>
      </figure>
    );
  },
);

CodeBlockOld.displayName = "CodeBlockOld";
